### ISSUE TITLE
Suggestion: Grids seperating the nodes. 

### ISSUE THREAD

**Issue by a-nldisr** [rchakode/realopinsight-oneinsight#1]
Hi, 

We have tried your interface in a test environment, i hope you do not mind a suggestion in the interface design. 

Currently in our Cloud environment we have various nodes with different cpu counts. Some nodes have 64 cores, some have 32 and others 8. In your current design it is difficult to see a difference where node X starts and stops. Example:

![image](https://cloud.githubusercontent.com/assets/1867776/8854636/28375522-3161-11e5-975f-78e85884fc8d.png)

To give a suggestion: Perhaps insert a set grid between each node with some whitespace and perhaps a single line to separate each node , this would help in visibility. I would suggest to set the grid space for every node based on the largest node in the cluster. 

Thanks for your current work so far! :+1:

**Comment by rchakode** [comment]
Hi @a-nldisr,

Thanks for your feedback. 
Your remark is very relevant, we'll work to improve the visualization in this way. 

Cheers

**Comment by a-nldisr** [comment]
Looking forward to the improvements! :+1:

**Comment by rchakode** [comment]
Please check down the latest commits and let me know what you think...

**Comment by a-nldisr** [comment]
Wow, great work! :+1: 
It works excellent: 
https://ui.hpccloud.surfsara.nl/oneinsight/frontend/

**Comment by rchakode** [comment]
Thanks for the feedback.

**Comment by rchakode** [comment]
Last point: From the link you shared with us (thanks again), I found a minor problem with tooltips (the turquoise color is not for 100% load). I fix that in my latest commit.

**Comment by a-nldisr** [comment]
Great work! :+1:

**Comment by rchakode** [comment]
hi @a-nldisr ,
I made some improvement in oneInsight that significantly improved your node grid here: https://ui.hpccloud.surfsara.nl/oneinsight/frontend/

Try it out and let me know.

Regards,

R.

**Comment by a-nldisr** [comment]
Hi @rchakode 
I no longer work at SURFsara, but i'll forward it to the guys there. Thanks!
