### ISSUE TITLE
GPU Support

### ISSUE THREAD

**Issue by a-nldisr** [rchakode/realopinsight-oneinsight#2]
In Opennebula GPU is now added as a resource, are there plans to add this to oneinsight?

**Comment by rchakode** [comment]
Hi @a-nldisr 
Thank you for the report, I'll manage to include the support of GPU in next versions of oneInsight.

**Comment by rchakode** [comment]
Hi @a-nldisr 

As I haven't yet have a computer with GPU in my development environment, can you please send me the XML file generated by the oneInsight cron script ?

You must find this file at the following location ```/opt/oneinsight/backend/hostpool.xml```

You can send it by private email if you think that's confidential, it would help us to add the support of GPU insight.

**Comment by a-nldisr** [comment]
Hi, you can download it from here: https://ui.hpccloud.surfsara.nl/oneinsight/backend/hostpool.xml

**Comment by rchakode** [comment]
Hi,
Thank you.

After an analysis of this sample, it seems that OpenNebula does not  provide any specific monitoring data concerning the GPU usage (the below excerpt shows the list of available monitoring data). Hence there is no room for improvement regarding oneInsight.


```
        <CLUSTER>GPU Oort</CLUSTER>
        <HOST_SHARE>
            <DISK_USAGE>0</DISK_USAGE>
            <MEM_USAGE>0</MEM_USAGE>
            <CPU_USAGE>0</CPU_USAGE>
            <MAX_DISK>748892</MAX_DISK>
            <MAX_MEM>255695504</MAX_MEM>
            <MAX_CPU>3200</MAX_CPU>
            <FREE_DISK>708400</FREE_DISK>
            <FREE_MEM>260724992</FREE_MEM>
            <FREE_CPU>3200</FREE_CPU>
            <USED_DISK>2428</USED_DISK>
            <USED_MEM>3359124</USED_MEM>
            <USED_CPU>0</USED_CPU>
            <RUNNING_VMS>0</RUNNING_VMS>
```

**Comment by a-nldisr** [comment]
Interesting, thanks for looking into this!
